// helloWorlds/react/react-hello/src/App.js
import React, { Component } from 'react';
import {
  BrowserRouter as Router,
  Route,
  Link
} from 'react-router-dom';
import HelloWorld from './HelloWorld/HelloWorld';
import SubComp from './SubComp/SubComp';

import './App.css';

class App extends Component {
  render() {
    return (
        <Router>
            <div className="content">
              <div className="links">
                <Link to="/">Home</Link>
                <Link to="/main">Main</Link>
                <Link to="/sub">Sub</Link>
              </div>
              <div className="view">
                <Route exact path="/" component={Home} />
                <Route path="/main" component={HelloWorld} />
                <Route path="/sub" component={SubComp} />
              </div>
            </div>
        </Router>
    );
  }
}

const Home = () => (
  <div className="home">
    <div className="the-div">
      <h1>cedsci react hello world</h1>
      <HelloWorld/>
    </div>
  </div>
);

export default App;

// helloWorlds/ng/ng-hello/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'body',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],

})
export class AppComponent {
  title = 'cedsci hello world';

  constructor() {
  }

}

<nav>
    <a routerLink="/" routerLinkActive="active">Home</a>
    <a routerLink="/main" routerLinkActive="active">Main</a>
    <a routerLink="/sub" routerLinkActive="active">Sub</a>
  </nav>
<div class="the-div">
  <router-outlet></router-outlet>
</div>
